import json
import os
from datetime import datetime
from typing import List, Dict

from src.collector import DataCollector
from src.analyzer import IndicatorEngine

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
os.makedirs(DATA_DIR, exist_ok=True)

class ReportGenerator:
    """Generate market intelligence reports and sync to README."""
    
    ASSETS = [
        ("GC=F", "XAU/USD (Gold Futures)"),
        ("BTC-USD", "BTC/USD (Bitcoin)"),
        ("ETH-USD", "ETH/USD (Ethereum)"),
    ]

    @staticmethod
    def run_full_pipeline() -> List[Dict]:
        """Orchestrate data collection, analysis, and reporting."""
        results = []
        
        for ticker, label in ReportGenerator.ASSETS:
            df = DataCollector.fetch_market_data(ticker)
            if df is None:
                print(f"[WARNING] No data for {label}")
                continue
            
            df_with_ind = IndicatorEngine.apply_indicators(df)
            
            signal = IndicatorEngine.generate_signal(df_with_ind, label)
            results.append(signal)
            
            # Save raw data as parquet
            fname = f"{ticker.replace('-', '_').lower()}.parquet"
            filepath = os.path.join(DATA_DIR, fname)
            df_with_ind.to_parquet(filepath, index=False)
            print(f"[Data] Saved to {filepath}")
        
        # Save signals as JSON for the README template
        signals_path = os.path.join(DATA_DIR, "signals.json")
        with open(signals_path, "w") as f:
            json.dump(results, f, indent=2)
        print(f"[Data] Signals saved to {signals_path}")
        
        return results

    @staticmethod
    def generate_readme(signals: List[Dict]) -> str:
        """Render README.md with live market data."""
        now = datetime.now().strftime("%Y-%m-%d %H:%M UTC+7")
        
        signal_rows = ""
        for s in signals:
            emoji = "🟢" if s['action'] == "BUY" else ("🔴" if s['action'] == "SELL" else "⚪")
            signal_rows += (
                f"| {s['asset']} | ${s['price']:,.2f} | {emoji} **{s['action']}** "
                f"| {s['rsi']} | {s['trend']} |\n"
            )
        
        return f"""# 📡 Alpha Radar — Automated Market Intelligence

> **Portfolio-ready Project** — Automated daily market pipeline with technical analysis indicators, CI/CD via GitHub Actions, and version-controlled data storage.

[![Tests](https://github.com/azizyuwono/alpha-radar/actions/workflows/run-pipeline.yml/badge.svg)](https://github.com/azizyuwono/alpha-radar/actions)

## 🔍 Live Signals

_Last updated: {now}_

| Asset | Price | Signal | RSI (14) | Trend |
|-------|-------|--------|----------|-------|
{signal_rows}

---

## 🏗 Architecture

```mermaid
graph TD
    A[YFinance API] --> B[DataCollector]
    B --> C[IndicatorEngine]
    C --> D[ReportGenerator]
    D --> E[data/*.parquet]
    D --> F[README.md]
    F --> G[Git Commit & Push]
    G -->|Daily 08:00 WIB| H[GitHub Actions]
    H --> A
```

### How it works
1. **GitHub Actions** triggers daily at **01:00 UTC (08:00 WIB)**.
2. `DataCollector` pulls the latest market data via Yahoo Finance API.
3. `IndicatorEngine` applies **EMA (9/21)**, **RSI (14)**, and **Bollinger Bands**.
4. `ReportGenerator` logs, saves raw Parquet data, and writes the README table above.
5. Changes are committed and pushed — your contribution graph stays green without manual effort.

### Tech Stack
| Layer | Technology |
|-------|-----------|
| **Language** | Python 3.11 |
| **Testing** | `pytest` (4 unit tests) |
| **Automation** | GitHub Actions CI/CD |
| **Data Storage** | Apache Parquet |
| **Data Source** | Yahoo Finance API |

## 🚀 Getting Started

```bash
git clone https://github.com/azizyuwono/alpha-radar.git
cd alpha-radar
pip install -r requirements.txt
python -m pytest tests/
python src/main.py
```

---

_Generated by **Alpha Radar** © {datetime.now().year} Aziz Yuwono_
"""

if __name__ == "__main__":
    signals = ReportGenerator.run_full_pipeline()
    readme = ReportGenerator.generate_readme(signals)
    
    readme_path = os.path.join(os.path.dirname(__file__), "..", "README.md")
    with open(readme_path, "w") as f:
        f.write(readme)
    
    print("[Done] README.md synced with live signals.")
